export const FETCH_INCIDENTS = 'FETCH_INCIDENTS';
export const FETCH_INCIDENTS_SUCCESS = 'FETCH_INCIDENTS_SUCCESS';
export const NOW_DROPDOWN_PANEL_ITEM_CLICKED = 'NOW_DROPDOWN_PANEL#ITEM_CLICKED';
export const DELETE_INCIDENT_CLICKED = 'DELETE_INCIDENT_CLICKED';
export const DELETE_INCIDENT_SUCCESS = 'DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_FAILED = 'DELETE_INCIDENT_FAILED';
export const DELETE_INCIDENT = 'DELETE_INCIDENT';
export const OPEN_INCIDENT_MODAL = 'OPEN_INCIDENT_MODAL';
export const NOW_MODAL_FOOTER_ACTION_CLICKED = 'NOW_MODAL#FOOTER_ACTION_CLICKED';
export const NOW_MODAL_OPENED_SET = 'NOW_MODAL#OPENED_SET';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const NOW_INPUT_VALUE_SET = 'NOW_INPUT#VALUE_SET';
export const SEARCH_BUTTON_CLICKED = 'SEARCH_BUTTON_CLICKED';
export const RESET_BUTTON_CLICKED = 'RESET_BUTTON_CLICKED';
export const NOW_DROPDOWN_ITEM_CLICKED = 'NOW_DROPDOWN#SELECTED_ITEMS_SET';
export const FETCH_INCIDENT_STATES = 'FETCH_INCIDENT_STATES';
export const FETCH_INCIDENT_STATES_SUCCESS = 'FETCH_INCIDENT_STATES_SUCCESS';
export const INITIAL_SEARCH_STATE = {
    number: '',
    shortDescription: '',
    assignmentGroup: '',
    assignedTo: '',
    selectedStateIds: []
};
